apiVersion: v1
kind: Service
metadata:
  name: bookings
spec:
  selector:
    app: bookings
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30000
  type: NodePort
