# compose file for running the application, declaring services
version: '3.8'

services:
  wildfly:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: events
      MYSQL_USER: devuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
