version: '3.8'
services:
  app:
    image: tonnyseko/bookings:v1.0
    expose:
      - 8080
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3309:3306
