---
- hosts: localhost
  tasks:
  - name: Apply MySQL deployment
    command: kubectl apply -f /home/tonny/clones/event-bookings/mysql-deployment.yml

  - name: Apply MySQL service
    command: kubectl apply -f /home/tonny/clones/event-bookings/mysql-service.yml

  - name: Apply application deployment
    command: kubectl apply -f /home/tonny/clones/event-bookings/app-deployment.yml

  - name: Apply application service
    command: kubectl apply -f /home/tonny/clones/event-bookings/app-service.yml
