version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tonnyseko/bookings
    docker:
      - image: cimg/openjdk:17.0.9-node

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:v1.0 .
            docker tag $IMAGE_NAME:v1.0 $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker tag $IMAGE_NAME:v1.0 $IMAGE_NAME:latest
      - run:
          name: List directory contents
          command: ls -lA
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:v1.0
            docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
